{% set name = "ptyrad" %}
{% set version = "1.0.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ptyrad-{{ version }}.tar.gz
  sha256: fcbf4560d94069b49fd9d3e668913d2dca2984924c3260f6088c810bcd68f76e

build:
  entry_points:
    - ptyrad = ptyrad.cli.entry:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - accelerate
    - h5py
    - jupyter
    - matplotlib-base
    - optuna
    - pydantic
    - pytorch >=2.4
    - scikit-learn
    - scipy
    - tifffile
    - torchvision
    - zarr


test:
  imports:
    - ptyrad
  commands:
    - pip check
    - ptyrad --help
    - python -m ptyrad --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/chiahao3/ptyrad
  summary: 'PtyRAD: Ptychographic Reconstruction with Automatic Differentiation'
  dev_url: "https://github.com/chiahao3/ptyrad"
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chiahao3
